Q1. FIND THE TITLE OF EACH FILM
SELECT title FROM movies;

Q2. FIND THE DIRECTOR OF EACH FILM
SELECT director FROM movies;

Q3. FIND TITLE AND DIRECTOR OF EACH FILM
SELECT titlr, director FROM movies;

Q4. FIND TITLE AND YEAR OF EACH FILM
SELECT  title, year FROM movies;

Q5. FIND ALL THE INFORMATION ABOUT EACH FILM
SELECT * FROM movies;